Quiron_Medical/Models/Q/Geography/State.cs
using Quiron_Medical.Models.DAL;
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using System.Linq;
using System.Web;

namespace Quiron_Medical.Models.Geography
{
    public class State
    {
        #region Properties
        public long ID { get; set; }
        [Required()]
        [StringLength(450)]
        [Display(Name = "Estado")]
        //[Index("UK_State", 1, IsUnique = true)]
        public String Name { get; set; }
        [Required()]
        [Display(Name = "PaisID")]        
        //[Index("UK_State", 2, IsUnique = true)]
        public long CountryID { get; set; }
        
        public virtual List<City> Cities { get; set; }
        //public virtual Country Country { get; set; }
        #endregion

        #region Construction
        public State() { }
        #endregion

        #region Methods
        public List<State> GetStatesByCountryID(long countryID)
        {
            List<State> states = new List<State>();
            QuironContext context = new QuironContext();
            states = context.States.Where(x => x.CountryID == countryID).ToList();
            return states;
        }
        #endregion
    }
}

Quiron_Medical/Controllers/Q/CitiesController.cs
using Quiron_Medical.Models.DAL;
using Quiron_Medical.Models.Geography;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Net;
using System.Web;
using System.Web.Mvc;

namespace Quiron_Medical.Controllers
{
    public class CitiesController : Controller
    {
        QuironContext context = new QuironContext();
        // GET: Cities
        [ChildActionOnly()]
        public PartialViewResult _GetForState(long StateID)
        {
            ViewBag.StateID = StateID;
            List<City> cities = context.Cities.Where(x => x.StateID == StateID).ToList();
            return PartialView("_GetForState", cities);
        }

        // GET: Cities/Details/5
        public ActionResult Details(long? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            City city = context.Cities.Find(id);
            if (city == null)
            {
                return HttpNotFound();
            }
            return View(city);
        }

        public ActionResult BackToState(long? StateID)
        {
            return Redirect("~/States/Details/" + StateID);
        }
    }
}

Quiron_Medical/Controllers/Q/StatesController.cs
using Quiron_Medical.Models.DAL;
using Quiron_Medical.Models.Geography;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Net;
using System.Web;
using System.Web.Mvc;

namespace Quiron_Medical.Controllers
{
    public class StatesController : Controller
    {
        QuironContext context = new QuironContext();

        // GET: States
        [ChildActionOnly()]
        public PartialViewResult _GetForCountry(long CountryID)
        {
            ViewBag.CountryID = CountryID;
            List<State> states = context.States.Where(x => x.CountryID == CountryID).ToList();
            return PartialView("_GetForCountry", states);
        }

        // GET: States/Details/5
        public ActionResult Details(long? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            State state = context.States.Find(id);
            if (state == null)
            {
                return HttpNotFound();
            }
            return View(state);
        }

        public ActionResult BackToCountry(long? CountryID)
        {
            return Redirect("~/Countries/Details/" + CountryID);
        }
    }
}

Quiron_Medical/Views/States/Details.cshtml
@model Quiron_Medical.Models.Geography.State

@{
    ViewBag.Title = "Detalles";
}

<h2>Detalles</h2>

<div>
    <h4>Estado</h4>
    <hr />@Html.HiddenFor(x => x.CountryID)
    <dl class="dl-horizontal">
        <dt>
            @Html.DisplayNameFor(model => model.Name)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Name)
        </dd>

        @*<dt>
            @Html.DisplayNameFor(model => model.CountryID)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.CountryID)
        </dd>*@

    </dl>
</div>
<div>
    @Html.Action("_GetForState", "Cities", new { StateID = Model.ID })
</div>
<p>
    @Html.ActionLink("Editar", "Edit", new { id = Model.ID }) |
    @*@Html.ActionLink("Volver", "Details", new { id = Model.CountryID })*@
    @Html.ActionLink("Volver", "BackToCountry", new { CountryID = Model.CountryID })
</p>

Quiron_Medical/Views/States/_GetForCountry.cshtml
@model IEnumerable<Quiron_Medical.Models.Geography.State>
<ul>
    <li>
        <h4>Estados:</h4>
        <p>
            @Html.ActionLink("Nuevo", "Create")
        </p>
        <table class="table">
            <tr>
                <th>
                    @Html.DisplayNameFor(model => model.Name)
                </th>
                @*<th>
                        @Html.DisplayNameFor(model => model.CountryID)
                    </th>*@
                <th></th>
            </tr>

            @foreach (var item in Model)
            {
                <tr>
                    <td>
                        @Html.DisplayFor(modelItem => item.Name)
                    </td>
                    @*<td>
                            @Html.DisplayFor(modelItem => item.CountryID)
                        </td>*@
                    <td>
                        @Html.ActionLink("Editar", "Edit", new { id = item.ID }) |
                        @Html.ActionLink("Detalles", "Details", new { id = item.ID }) |
                        @Html.ActionLink("Eliminar", "Delete", new { id = item.ID })
                    </td>
                </tr>
            }

        </table>
    </li>
</ul>